### ISSUE TITLE
Images are HUGE on android phone Outlook App.

### ISSUE THREAD

**Issue by miamimabel** [TedGoas/Cerberus#277] opened 2022-02-01 19:44 UTC
When testing on my android, Outlook app, the image is stretched. Looks great on Outlook desktop and webmail.

Thanks in advance for any input you have!

See screenshot as a reference
![image-issue](https://user-images.githubusercontent.com/44374217/152039813-cceb4c9d-cd04-4882-909d-f451cf67f232.jpg)

**Comment by TedGoas** [comment] 2022-02-02 00:57
@miamimabel It looks like there is a `width: 100%` being applied somewhere. This is by design in the templates, but if this isn't the behavior you'd want you can remove it. Depending on which email template you're using, I'd try removing a `width: 100%` from an inline style or a `width: 100% !important` from a media query in the `<style>` tag in the `<head>`.

**Comment by TedGoas** [comment] 2022-02-06 14:17
Since this issue isn't a bug with the templates in this repo, I'll close this. Happy to keep chatting about your issue though.

**Closed as completed by TedGoas** 2022-02-06 14:17 UTC
